---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest"
    command: /usr/sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - default
provisioner:
  name: ansible
  inventory:
    links:
      hosts: test_inventory.ini
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
